import { Cupo } from "@app/shared/models/v2-disponibles";

export class DetalleDestinatario {
  idDestinatario: string;
  nombreDestinatario: string;
  idCuitDestinatario: string;
  id_destino: number;
  nombre_destino: string;
  id_producto: number;
  nombre_producto: string;
  total_cupos: number;
  por_asignar: number;
  por_vincular: number;
  ctg: number;
  sin_ctg: number;
  mas_50km: number;
  menos_50km: number;
  cargados: number;
  menos_50km_destino: number;
  en_destino: number;
  choferAsignado: number;
  rechazado: number;
  descargado: number;
  anulados: number;
  cupos: Cupo[];
  derivacion?: Derivacion;
}

// Generated by https://quicktype.io

export interface Derivacion {
  id: string;
  id_transportadora: string;
  transportadora: string;
  fecha_derivacion: Date;
  canal: string;
}

export class DetalleTransportadora {
  id_receptor: number;
  nombre_receptor: string;
  nombre_destino: string;
  id_destino: number;
  cuitReceptor: string;
  id_producto: number;
  nombre_producto: string;
  total_cupos: number;
  por_asignar: number;
  por_vincular: number;
  ctg: number;
  sin_ctg: number;
  mas_50km: number;
  menos_50km: number;
  cargados: number;
  menos_50km_destino: number;
  en_destino: number;
  descargado: number;
  rechazado: number;
  anulados: number;
  cupos: Cupo[];
  id_transportadora: string;
  transportadora: string;
  choferAsignado: number;
}
