
export class CupoAsignadoApi {
  asignado: string | null;
  cantHorasSalidaCamion: number | null;
  caratulaMercadoATermino: string | null;
  cartaPorte: string | null;
  codGrano: number | null;
  codLocalidadDestino: number | null;
  codLocalidadOrigen: number | null;
  consultadoXAFIP: string | null;
  cosecha: number | null;
  creado: string | null;
  creadoPor: number | null;
  created_at: string | null;
  ctg: number | null;
  cuitChoferAfip: string | null;
  cuitCorredorCAfip: string | null;
  cuitCorredorVAfip: string | null;
  cuitDestinatarioAfip: string | null;
  cuitDestinoAfip: string | null;
  cuitIntermediarioFleteAfip: string | null;
  cuitMercadoATerminoAfip: string | null;
  cuitOrigenAfip: string | null;
  cuitRemComercialAfip: string | null;
  cuitRepresentanteEntregadorAfip: string | null;
  cuitTransportistaAfip: string | null;
  destino: DestinosApi2;
  dominio: string | null;
  desvio: string | null;
  esAnulado: string | null;
  esRechazado: string | null;
  estado: string | null;
  estadoViaje: string | null;
  fecha: string | null;
  fechaActivado: string | null;
  fechaAnulado: string | null;
  fechaArribado: string | null;
  fechaCP_Carga: string | null;
  fechaCP_Vto: string | null;
  fechaCTG_Desde: string | null;
  fechaCTG_Hasta: string | null;
  fechaConfirmado: string | null;
  fechaDescargado: string | null;
  fechaDesviadoD: string | null;
  fechaDesviadoO: string | null;
  fechaRechazado: string | null;
  fechaRegresado: string | null;
  fechaTomado: string | null;
  id: number;
  idCuitChofer: string | null;
  idCuitCorredorC: string | null;
  idCuitCorredorV: string | null;
  idCuitDestinatario: string | null;
  idCuitDestino: string | null;
  idCuitIntermediario: string | null;
  idCuitIntermediario1: string | null;
  idCuitIntermediario2: string | null;
  idCuitIntermediarioFlete: string | null;
  idCuitMercadoATermino: number | null;
  idCuitOrigen: string | null;
  idCuitRemComercial: string | null;
  idCuitRepresentanteEntregador: string | null;
  idCuitTransportista: string | null;
  idCupo: number | null;
  idCupoEstado: number | null;
  idCupoTerminal: string | null;
  idEstadoEnPlanta: number | null;
  idTerminal: number | null;
  idTurnoDetalle: string | null;
  id_destino: number | null;
  id_entregador: number | null;
  id_localidad: string | null;
  id_pedido: number | null;
  id_producto: number | null;
  kmRecorrer: number | null;
  modificado: string | null;
  modificadoPor: number | null;
  nombreDestinatario: string | null;
  nombreDestino: string | null;
  nroContrato: string | null;
  nroEstablecimientoOrigen: string | null;
  nroPlantaRuca: string | null;
  pendienteGeneral:boolean;
  pesoNetoEstimado: number | null;
  recibido_de:string | null;
  recuperable: boolean;
  renspa: string | null;
  ultimaGeocalizacion: string | null;
  ultima_fecha_asignacion: string | null;
  ultima_latitud: string | null;
  ultima_longitud: string | null;
  ultimo: string | null;
  updated_at: string | null;
  vinculado: string | null;

  idCuitIntermediarioFleteFlete: string | null;
  nombreIntermediario1: string | null;
  nombreIntermediario2: string | null;
  pendiente: boolean | null;
  comentario: string | null;

}

// Generated by https://quicktype.io

export class CuposAsignar {
  codGrano: number | null;
  cartaPorte: string | null;
  cosecha: number | null;
  ctg: number | null;
  cuitChoferAfip: string | null;
  cuitCorredorCAfip: string | null;
  cuitCorredorVAfip: string | null;
  cuitDestinatarioAfip: string | null;
  cuitDestinoAfip: string | null;
  cuitIntermediarioFleteAfip: string | null;
  cuitMercadoATerminoAfip: string | null;
  cuitOrigenAfip: string | null;
  cuitRemComercialAfip: string | null;
  cuitRepresentanteEntregadorAfip: string | null;
  cuitTransportistaAfip: string | null;
  codLocalidadOrigen: number | null;
  codLocalidadDestino: number | null;
  desvio: string | null;
  dominio: string | null;
  estado: string | null;
  esAnulado: string | null;
  esRechazado: string | null;

  fecha: string | null;
  fechaCTG_Desde: string | null;
  fechaActivado: string | null;
  fechaArribado: string | null;
  fechaTomado: string | null;
  fechaConfirmado: string | null;
  fechaAnulado: string | null;
  fechaDesviadoO: string | null;
  fechaRegresado: string | null;
  fechaDesviadoD: string | null;
  fechaRechazado: string | null;
  fechaDescargado: string | null;
  fechaCTG_Hasta: string | null;
  fechaCP_Carga: string | null;
  fechaCP_Vto: string | null;
  id: number;
  idCuitDestinatario: string | null;
  idCupoEstado: number | null;
  idCupoTerminal: string | null;
  id_entregador: number | null;
  id_pedido: number | null;
  id_producto: number | null;
  id_destino: number | null;
  idCuitMercadoATermino: number | null;
  idCupo: number | null;
  idTerminal: number | null;
  idCuitOrigen: string | null;
  idCuitIntermediarioFlete: string | null;
  idCuitRemComercial: string | null;
  idCuitCorredorV: string | null;
  idCuitCorredorC: string | null;
  idCuitRepresentanteEntregador: string | null;
  idCuitDestino: string | null;
  idCuitIntermediarioFleteFlete: string | null;
  idCuitTransportista: string | null;
  idCuitChofer: string | null;
  idCuitIntermediario1: string | null;
  idCuitIntermediario2: string | null;
  nombreIntermediario1: string | null;
  nombreIntermediario2: string | null;

  idTurnoDetalle: string | null;
  renspa: string | null;
  nroEstablecimientoOrigen: string | null;
  pesoNetoEstimado: number | null;
  kmRecorrer: number | null;
  cantHorasSalidaCamion: number | null;
  nroContrato: string | null;
  nroPlantaRuca: string | null;
  idEstadoEnPlanta: number | null;
  creado: string | null;
  modificado: string | null;
  creadoPor: number | null;
  modificadoPor: number | null;
  consultadoXAFIP: string | null;
  asignado: string | null;
  nombreDestinatario: string | null;
  nombreDestino: string | null;
  pendiente: boolean | null;
  vinculado: string | null;
  caratulaMercadoATermino: string | null;
  comentario: string | null;
  habilitado?: boolean;
  asignados?: boolean;
  ultimo: string | null;
  ultima_fecha_asignacion: string | null;
  ultimaGeocalizacion: string | null;
  ultima_latitud: string | null;
  ultima_longitud: string | null;
}





export class ProductosApi {
  "id_producto": number;
  "pendientes": number;
  "total": number;
  "cupos": CupoAsignadoApi[];
}

export class DestinosApi {
  id_destino: number;
  productos: ProductosApi[];
}

export class Dadores {
  id_dador: number;
  destinos: DestinosApi[];
}

export class AsignadosDemanda {
  id_cupo: number;
  id_cupo_cliente: number;
  id_destino: number;
  id_estado_cupo: number;
  id_chofer: number;
  id_gestiona: number;
  alfanumericoCupo: string;
  fechaCupo: string;
  numeroContrato: string;
  cartaPorte: string;

}
export class Demandas {
  id_demanda_cupo: number;
  cantidad: number;
  asignado: number;
  fechaDesde: string;
  fechaHasta: string;
  observaciones: string;
  codigoCosecha: string;
  contrato: string;
  comprador: string;
  zona: string;
  id_gestiona: number;
  asignados: AsignadosDemanda[];
  id_demandante?: number;
  id_demandado?: number;
  id_producto?: number;
  nombreDemandante?: string;
  cuitDemandante?: string;
  nombreDemandado?: string;
  nombreProducto?: string;
  caratula_mtr?: string;
  asignar?: number;
}

export class ProductosDemanda {
  id_producto: number;
  demandas: Demandas[];
}

export class Demandantes {
  id_demandantes: number;
  productos: ProductosDemanda[];
}

export class DestinosApi2 {
  id: string;
  descripcion: string;
  id_localidad: string;
}

