// Generated by https://quicktype.io

export interface Inconsistencia {
  id:                            string;
  cartaPorte:                    string | null;
  fechaCarga:                    string | null;
  fechaVencimiento:              string | null;
  nombreTitular:                 string | null;
  idCuitTitula:                  string | null;
  nombreIntermediario:           string | null;
  idCuitIntermediario:           string | null;
  nombreRemitente:               string | null;
  idCuitRemComercial:            string | null;
  nombreCorredorComprador:       string | null;
  idCuitCorredorC:               string | null;
  nombreMercadoATermino:         string | null;
  idCuitMercadoATermino:         string | null;
  nombreCorredorVendedor:        string | null;
  idCuitCorredorV:               string | null;
  nombreEntregador:              string | null;
  idCuitRepresentanteEntregador: string | null;
  nombreDestinatario:            string | null;
  idCuitDestinatario:            string | null;
  nombreDestino:                 string | null;
  idCuitDestino:                 string | null;
  nombreIntermediarioFlete:      string | null;
  idCuitIntermediarioFlete:      string | null;
  nombreTransportista:           string | null;
  idCuitTransportista:           string | null;
  nombreChofer:                  string | null;
  idCuitChofer:                  string | null;
  granoNombre:                   string | null;
  tipoGrano:                     string | null;
  cosecha:                       string | null;
  nroContrato:                   string | null;
  granoPesadaDestino:            string | null;
  granoKgEstimado:               string | null;
  granoCalidad:                  string | null;
  granoConforme:                 string | null;
  granoCondicional:              string | null;
  granoPesoBruto:                string | null;
  granoPesoTara:                 string | null;
  granoPesoNeto:                 string | null;
  granoObservaciones:            string | null;
  procedenciaEstablecimiento:    string | null;
  procedenciaDireccion:          string | null;
  procedenciaLocalidad:          string | null;
  procedenciaProvincia:          string | null;
  destinoGranoDireccion:         string | null;
  destinoGranoLocalidad:         string | null;
  destinoGranoProvincia:         string | null;
  transporteCamion:              string | null;
  transporteAcoplado:            string | null;
  transporteTarifaReferencia:    string | null;
  transporteTarifa:              string | null;
  kmRecorrer:                    string | null;
  transportePagadorFlete:        string | null;
  transporteFletePago:           string | null;
  destinoFechaArribo:            string | null;
  destinoHoraArribo:             string | null;
  destinoFechaDescarga:          string | null;
  destinoHoraDescarga:           string | null;
  destinoNumeroTurno:            string | null;
  destinoPesoBruto:              string | null;
  destinoPesoTara:               string | null;
  destinoPesoNeto:               string | null;
  destinoObservaciones:          string | null;
  desvioCuitDestino:             string | null;
  desvioCuitDestinatario:        string | null;
  desvioDomicilio:               string | null;
  desvioLocalidad:               string | null;
  nroPlantaRuca:                 string | null;
  desvioFecha:                   string | null;
  desvioOrdenadoPor:             string | null;
  numeroMatriculaRecibidor:      string | null;
  numeroMatriculaEntregador:     string | null;
  auditorias:                    Auditoria[];
}

export interface Auditoria {
  id:             string;
  id_cupo:        string;
  campo:          string;
  valor_actual:   string;
  valor_anterior: string;
  create_at:      string;
  nombreAnterior: string;
}


