
export class MagypCadena {
   id: number;
   descripcion: string;
}

export class MagypAutoridad {
  id: number;
  descripcion: string;
}


export interface Test {
  id:                   number;
  resultado:            number;
  resultadoString?:     string;
  fecha:                string;
  id_localidad:         number;
  id_autoridad_salud:   null;
  seguimiento:          number;
  seguimientoString?:   string;
  id_transportista:     number;
  app:                  number;
  appString?:           string;
  transportista:        Transportista;
  nombreAutoridadSalud: string;
  nombreProvincia:      string;
  nombreLocalidad:      string;
}

export interface Transportista {
  id:              number;
  cuit:            string;
  nombre_completo: string;
  patente:         string;
  telefono:        string;
  id_cadena:       null;
  observaciones:   string;
  nombreCadena:    null;
}

// Generated by https://quicktype.io

export interface ViajesSeguimiento {
  fechaActivado:   string;
  fechaTurno:      string;
  fechaArribado:   string;
  fechaDescargado: string;
  localidadOrigen: string;
  latitudOrigen:   number;
  longitudOrigen:  number;
  terminalDestino: string;
  latitudDestino:  number;
  longitudDestino: number;
}

// Generated by https://quicktype.io

export interface Transpor {
  id:              number;
  cuit:            string;
  nombre_completo: string;
  patente:         string;
  telefono:        string;
  id_cadena:       number;
  observaciones:   string;
  nombreCadena:    string;
  ultimoTest:      UltimoTest;
}

export interface UltimoTest {
  fecha:              string;
  seguimiento:        string;
  resultado:          string;
  seguimientoString:  string;
  resultadoString:    string;
}


