import { Viaje } from './viaje';
//import { Origen } from './origen';
//import { ZonaDestino} from './zona-destino';
import { Product } from './product.model';
import { Estado } from './estado';
import { Descarga } from './descarga';
import { Cupo } from './cupo';
export class Pedido {
  id: string;
  fecha_desde: string;
  fecha_hasta: string;
  id_origen: string;
  id_zona_destino: string;
  id_cliente: string;
  id_centro: string;
  id_destinatario: string;
  id_observador: string;
  id_generador: string;
  id_operador: string;
  cantidad: number;
  reduccion: number;
  id_producto: string;
  bloqueado: number;
  nombre_destinatario: string;
  nombre_generador: string;
  nombre_cliente: string;
  nombre_centro: string;
  nombre_observador: string;
  zonaDestino: ZonaDestino;
  origen: Origen;
  producto: Product;
  viaje_asignados: number;
  viajes: Viaje;
  estados: Estado;
  ocultar: number;
  tipo_pedido: string;
  solicitud: number;
  id_pedido_padre: number;
  id_lista: number;
  viajes_asignados: number;
  postulados: string;
  tiene_cupo?: number;
  viajes_bloqueados?: number;
  desvios?: number;
  _fecha_desde?: string;
  _fecha_hasta?: string;
  cupos: Cupo[];
}
// Generated by https://quicktype.io

export class PedidoAsignar {
  id: number;
  fecha_desde: string;
  fecha_hasta: string;
  id_origen: number;
  id_zona_destino: number;
  id_destino: null;
  id_cliente: number;
  id_centro: number;
  cantidad: number;
  reduccion: number;
  id_producto: number;
  bloqueado: number;
  oculto: number;
  id_operador: null;
  id_observador: null;
  solicitud: number;
  id_generador: number;
  id_pedido_padre: null;
  tipo: number;
  contador: number;
  difundido: number;
  contrato: string;
  observaciones: string;
  id_lista: null;
  nombre_cliente: string;
  nombre_centro: string;
  nombre_observador: null;
  nombre_generador: string;
  viajes_asignados_propios: number;
  viajes_asignados: number;
  estados: Estados;
  cupos: Cupo[];
  zonaDestino: ZonaDestino;
  producto: Producto;
  origen: Origen;
  viajes_bloqueados: number;
  desvios: number;
  tipo_pedido: string;
  soy_padre: boolean;
  viajes_mios: number;
  viajes_x_asignar: number;
  background: string;
  title_background: string;  //pintar el title de las tarjetas.
  tooltip: string;
  disponibles: string;
  postulados: string;
  intermediarios_postulados: string;
  _fecha_desde: string;
  _fecha_hasta: string;
  posee_cupo_fer: number;
  calesita: number;
  contrata?: number;
  editable?: boolean;
}


export interface Estados {
  Pendiente: string;
  A_Km_de_origen: number;
  Cargado: number;
  A_km_de_destino: number;
  En_destino: number;
  Conforme: number;
  Rechazado: number;
  Esperando: number;
  Descargado: number;
}

export interface Origen {
  id: number;
  id_localidad: number;
  descripcion: string;
  direccion: string;
  nombre_contacto: string;
  telefono: string;
  email: string;
  bloqueado: number;
  imagen: number;
  id_persona_rol: number;
  longitud: number;
  latitud: number;
  id_zona_destino: null;
  domicilio: null;
  id_tipo_destino: null;
  id_situacion_puerto: null;
  horas_atraso: null;
  CodigoPlantaOncca: null;
  hora_corte: null;
}

export interface Producto {
  id: number;
  descripcion: string;
  cupo_obligatorio: number;
  codigo: number;
}

export interface ZonaDestino {
  id: number;
  descripcion: string;
  latitud: string;
  longitud: string;
}

