
export class V2Disponibles {
  listado: Listado[];
  detalles: Detalles;
}

export class Dadore {
  id_dador: number;
  destinos: Destino[];
}
export class Listado {
  idCuitDestinatario: string;
  destinos: Destino[];
}

export class Receptore {
  id_dador: number;
  destinos: Destino[];
}

export interface Destino {
  id_destino: number;
  productos: Producto[];
}

export interface Producto {
  id_producto: number;
  pendientes: number;
  total: number;
  cupos: Cupo[];
}

export class Cupo {
  id: string;
  idCupoTerminal: string;
  fecha: string;
  idCuitDestinatario: string;
  cosecha: string;
  cartaPorte: string;
  ctg: string;
  idCupoEstado: string;
  fechaCTG_Desde: string;
  ultimaGeocalizacion: null | string;
  id_entregador: null | string;
  id_pedido: null | string;
  estado: string;
  id_producto: string;
  id_destino: string;
  idCuitMercadoATermino: null | string;
  dominio: string;
  fechaActivado: string;
  fechaArribado: null | string;
  fechaTomado: null | string;
  fechaConfirmado: null | string;
  fechaAnulado: null | string;
  fechaDesviadoO: null | string;
  fechaRegresado: null | string;
  fechaDesviadoD: null | string;
  fechaRechazado: null | string;
  fechaDescargado: null | string;
  codGrano: string;
  cuitChoferAfip: string;
  cuitCorredorCAfip: string;
  cuitCorredorVAfip: string;
  cuitDestinatarioAfip: string;
  cuitDestinoAfip: string;
  cuitIntermediarioFleteAfip: string;
  cuitMercadoATerminoAfip: string;
  cuitOrigenAfip: string;
  cuitRemComercialAfip: string;
  cuitRepresentanteEntregadorAfip: string;
  cuitTransportistaAfip: string;
  esAnulado: string;
  esRechazado: string;
  idCupo: string;
  idTerminal: string;
  idCuitOrigen: string;
  idCuitIntermediario: string;
  idCuitRemComercial: string;
  idCuitCorredorV: null | string;
  idCuitCorredorC: null | string;
  idCuitRepresentanteEntregador: null | string;
  idCuitDestino: null | string;
  idCuitIntermediarioFlete: null | string;
  idCuitTransportista: null | string;
  idCuitChofer: null | string;
  nombreIntermediario1: string | null;
  idCuitIntermediario1: string | null;
  nombreIntermediario2: string | null;
  idCuitIntermediario2: string | null;
  fechaCTG_Hasta: null | string;
  fechaCP_Carga: null | string;
  fechaCP_Vto: null | string;
  codLocalidadOrigen: null | string;
  codLocalidadDestino: null | string;
  desvio: null | string;
  idTurnoDetalle: null | string;
  renspa: null | string;
  nroEstablecimientoOrigen: null | string;
  pesoNetoEstimado: null | string;
  kmRecorrer: null | string;
  cantHorasSalidaCamion: null | string;
  nroContrato: null | string;
  nroPlantaRuca: null | string;
  idEstadoEnPlanta: null | string;
  creado: null | string;
  modificado: null | string;
  creadoPor: null | string;
  modificadoPor: null | string;
  consultadoXAFIP: null | string;
  ultima_latitud: null | string;
  ultima_longitud: null | string;
  asignado: null | string;
  ultimo: null | string;
  vinculado: null | string;
  nombreDestino: null | string;
  nombreDestinatario: null | string;
  estadoViaje: null | string;
  destino: Destino;
  cupoAsignadoUltimo: CupoAsignadoUltimo;
  estadoCalculado: string;
  pendienteGeneral: string;
  caratulaMercadoATermino: string | null;
  comentario: string | null;
  recuperable: boolean;
  idCuitChoferAsignado: any;
  choferAsignado: any;
}

export interface Derivacion {
  id: string;
  id_transportadora: string;
  derivacion: string;
}

export interface CupoAsignadoUltimo {
  id: string;
  id_cupo: string;
  dadorCuit: string;
  receptorCuit: string;
  primero: string;
  ultimo: string;
  vinculado: string;
  id_demanda: null | string;
  nroContrato: string;
}

export interface Destino {
  id: string;
  descripcion: string;
}



export interface IDDestinatario {
  nombreDador: string;
}
export interface IDReceptor {
  nombreReceptor: string;
}

export interface IDDestino {
  nombreDestino: string;
  s_puerto: SPuerto | null;
}

export enum SPuerto {
  OperandoNormal = "Operando normal",
  OperativoConDemora = "Operativo con demora",
}

export interface IDProducto {
  nombreProducto: string;
}


// Generated by https://quicktype.io

export class Detalles {
  destinatario: { [key: string]: Destinatario };
  destino: { [key: string]: Destino };
  producto: { [key: string]: Producto };
  receptor: { [key: string]: Receptor };
}
export class Detalles2 {
  destinatarios: { [key: string]: Destinatarios };
  destino: { [key: string]: Destino };
  producto: { [key: string]: Producto };
  corredor_demanda: { [key: string]: CorredorDemanda };
  corredor_contraparte: { [key: string]: CorredorContraparte };
  zonas: { [key: string]: Zonas };
}

export interface Destinatarios {
  cuit: string;
  razon_social: string;
}
export interface Destinatario {
  idCuitDestinatario: string;
  nombreDestinatario: string;
}

export interface Destino {
  id: string;
  nombreDestino: string;
  s_puerto: string;
}

export interface Producto {
  id: string;
  nombreProducto: string;
}

export interface Receptor {
  receptorCuit: string;
  nombreReceptor: null | string;
}
export interface Zonas {
  id: string;
  nombreZona: null | string;
}
export interface CorredorDemanda {
  cuit: string;
  razon_social: null | string;
  esCorredor: null | string;
}
export interface CorredorContraparte {
  cuit: string;
  razon_social: null | string;
  esCorredor: null | string;
}




