// Generated by https://quicktype.io

import { derivacionObject } from "../components/cupo/seguimiento/seguimiento.component";

export interface Cupo {
  receptorCuit: string | null;
  nombreReceptor: string | null;
  esCorredor: string | null;
  nroContrato: null,
  id_destino: string | null;
  id_producto: string | null;
  idCuitDestinatario: string | null;
  nombreDestinatario: string | null;
  idCuitDestino: string | null;
  nombreDestino: string | null;
  asignado: string | null;
  cumplido: string | null;
}



export interface Seguimiento {
  asignado: Asignados[];
  devoluciones: Devoluciones[];
  demandas: Demanda[];
  receptores: { [key: string]: Receptore };
  productos: { [key: string]: Producto };
}

export interface Demanda {
  id_demanda_cupo: string;
  fechaCupo: string;
  contraparte: null | string;
  cantidad: string;
  asignado: string;
  contrato: null | string;
  destinatario: null | string;
  id_producto: string;
  cuit: string;
  usada: boolean;
  estado: string;
  observaciones: null | string;
}

export interface Asignados {
  cuit: string;
  id_demanda: null;
  nroContrato: null;
  idCuitDestinatario: string;
  nombreDestinatario: string;
  id_destino: null;
  nombreDestino: string;
  id_producto: string;
  devueltos: string;
  asignados: string;
  cumplidos: string;
  estado: string;
  choferes_vinculados: string;
  derivacion?:derivacionObject[];
}
export interface Devoluciones {
  cuit: string;
  id_demanda: null;
  nroContrato: null;
  idCuitDestinatario: null;
  nombreDestinatario: null;
  idCuitDestino: null;
  nombreDestino: null;
  id_producto: string;
  devueltos: string;
}


export interface Producto {
  id: string;
  descripcion: string;
}

export interface Receptore {
  cuit: string;
  razon_social: string;
  esCorredor: string;
}

export class DestinatarioV3 {
  id: string;
  cuit: string;
  razon_social: string;
  destinos: ItemsCuit[];
  ccpp?: ItemsCuit[];
  rte?: ItemsCuit[];
  corredores?: CorredorV3[];
  contrapartes?: ItemsBasico[];
}
export class CorredorV3 {
  id: number;
  descripcion: string;
  contrapartes: ItemsBasico[];
}
export class ItemsCuit {
  id: number;
  descripcion: string;
  cuit: string;
}
export interface ItemsRazonSocial {
  id?: string;
  razon_social?: string;
  cuit?: string;
}
export class ItemsBasico {
  id: number;
  descripcion: string;
}




