import {
  Component,
  OnInit,
  ViewChild,
  AfterViewInit,
  Input,
  Output,
  EventEmitter,
} from "@angular/core";

import {
  MatPaginator,
  MatSort,
  MatTableDataSource,
  MatDialog,
  MatDialogRef,
  MatSnackBar,
  DateAdapter,
  MAT_DATE_FORMATS,
  MAT_DATE_LOCALE,
} from "@angular/material";
import { tap } from "rxjs/operators";
import { AppErrorService } from "app/shared/services/app-error/app-error.service";
import { AppAtencionService } from "app/shared/services/app-atencion/app-atencion.service";
import { AppConfirmService } from "app/shared/services/app-confirm/app-confirm.service";
import { AppAlertService } from "app/shared/services/app-alert/app-alert.service";
import { AppLoaderService } from "app/shared/services/app-loader/app-loader.service";
import { FormGroup, FormControl } from "@angular/forms";
import { Router } from "@angular/router";
import { Subscription } from "rxjs";
import * as moment from "moment";
import { NomencladoresService } from "app/shared/services/nomencladores.service";
import {
  V2Disponibles,
  Cupo,
  Dadore,
  Detalles,
} from "app/shared/models/v2-disponibles";
import { CupoService } from "../cupo.service";
import { HomeService } from "../../home/home.service";
import { RecuperarComponent } from "../recuperar/recuperar.component";
import {
  AppDateAdapter,
  APP_DATE_FORMATS,
} from "@shared/helpers/date.adapter";
import { DetalleConsolidadoComponent } from "../detalle-consolidado/detalle-consolidado.component";
import { UserService } from "app/shared/services/user.service";
import { MessageService } from "app/shared/services/message.service";

export class DetalleReceptor {
  id_receptor: number;
  nombre_receptor: string;
  cuitReceptor: string;
  id_producto: number;
  nombre_producto: string;
  total_cupos: number;
  por_asignar: number;
  por_vincular: number;
  ctg: number;
  sin_ctg: number;
  mas_50km: number;
  menos_50km: number;
  cargados: number;
  menos_50km_destino: number;
  en_destino: number;
  descargado: number;
  anulados: number;
  cupos: Cupo[];
  recuperar: boolean;
}

export class CupoEspecifico {
  alfanumericoCupo: string;
  asignado: boolean;
  vincula: number;
  id_receptor: null | number;
  cartaPorte: null | string;
  codigoCosecha: null | string;
  cuitMercadoTermino: null | string;
  datoComplejo: null | string;
  destinatarioCuit: string;
  estado: string;
  estado_viaje: null | string;
  estadoCTG: null | string;
  fechaCupo: string;
  id_cupo: number;
  id_cupo_cliente: number;
  id_entregador: null;
  id_producto: number;
  numeroCTG: number | null;
  numeroContrato: null | string;
  observaciones: null | string;
  usado: number;
  destino?: null | string;
  id_destino?: number | null;
}

// Generated by https://quicktype.io

@Component({
  selector: "app-asignados-receptor",
  templateUrl: "./asignados-receptor.component.html",
  styleUrls: ["./asignados-receptor.component.scss"],
  providers: [
    {
      provide: DateAdapter,
      useClass: AppDateAdapter,
    },
    {
      provide: MAT_DATE_FORMATS,
      useValue: APP_DATE_FORMATS,
    },
    {
      provide: MAT_DATE_LOCALE,
      useValue: "es-AR",
    },
  ],
})
export class AsignadosReceptorComponent implements OnInit {
  @Input() fecha: string;
  @Input() listado;
  @Input() detalles;
  @Output() cambiarFecha = new EventEmitter();

  cuposDisponibles: Cupo[] = [];
  filtrarForm: FormGroup;
  now = moment(new Date()).format("YYYY-MM-DD");
  seleccionados = [];
  isCustomizerOpen2: boolean = false;
  public getItemSub: Subscription;
  dataSource = new MatTableDataSource();
  displayedColumns: string[] = [
    "first_color",
    "receptor",
    "total",
    "ctg",
    "sin_ctg",
    "en_destino",
    "descargados",
    //"anulados",
    "recuperar",
    //"acciones"
  ];
  @ViewChild(MatPaginator) paginator: MatPaginator;
  @ViewChild(MatSort) sort: MatSort;
  messages = {
    emptyMessage: `
      <div>
        <span class="classname">No hay Cupos Disponibles</span>
      </div>
    `,
  };
  filtro = {
    fecha: this.homeService.formatoFecha(new Date().toString(), "amd", "-"),
    id_producto: 1,
  };
  filtro1 = {
    fecha: this.homeService.formatoFecha(new Date().toString(), "amd", "-"),
    id_producto: 1,
    id_receptor: 0,
    estado: "",
  };
  minDate = new Date();
  public pageSize = 20;
  public totalSize = 0;
  filtroespeciales = [];
  otrosproductos = [];
  f = 1;
  DATA: any[];

  dataV2: V2Disponibles;
  cuposDisponiblesApi: Dadore[];
  detallesDisponiblesApi: Detalles;
  detallesReceptor: DetalleReceptor[];
  myname: string = "";
  mycuit: string = "";
  myid_receptor: number = 0;
  private subscription: Subscription;
  message: any;

  constructor(
    private cupoService: CupoService,
    private nomencladoresService: NomencladoresService,
    private dialog: MatDialog,
    private errorService: AppErrorService,
    private atencionService: AppAtencionService,
    private confirmService: AppConfirmService,
    private alertService: AppAlertService,
    private loader: AppLoaderService,
    private snack: MatSnackBar,
    public router: Router,
    public homeService: HomeService,
    private userService: UserService,
    private messageService: MessageService
  ) {
    this.subscription = this.messageService
      .getMessage()
      .subscribe((message) => {
        this.message = message;
        switch (this.message.text) {
          case "AsignadosReceptor":
            this.loadDataV2(this.message.data);
            break;
          default:
            break;
        }
      });
  }

  ngOnInit() {
    this.myname = localStorage.getItem("nameUser");
    this.mycuit = localStorage.getItem("cuit_cuil");
    this.dataSource.paginator = this.paginator;
    this.paginator._intl.itemsPerPageLabel = "Elementos por Página";
    this.paginator._intl.nextPageLabel = "Siguiente";
    this.paginator._intl.firstPageLabel = "Primero";
    this.paginator._intl.lastPageLabel = "Último ";
    this.paginator._intl.previousPageLabel = "Anterior";
    this.dataSource.sort = this.sort;
    this.paginator.pageIndex = 0;
    this.paginator.pageSize = 20;
    this.paginator._intl.getRangeLabel = (page: number, pageSize: number, length: number) => {
      const start = page * pageSize + 1;
      const end = (page + 1) * pageSize;
      return `${start} - ${end} de ${length}`;
    };
    this.filtrarForm = new FormGroup({
      selectedProducto: new FormControl(this.filtro.id_producto),
      selectedFecha: new FormControl(new Date(this.fecha + " 12:00:00")),
    });
    this.userService
      .getIdPersonaRol(localStorage.getItem("rol"))
      .subscribe((data) => {
        this.myid_receptor = data.data;
        //this.loadDataV2();
      });
    let data = {
      listado: [],
    };
    if (this.listado.length > 0) {
      const data = {
        listado: this.listado,
        detalles: this.detalles,
      };
      this.loadDataV2(data);
    }
  }

  loadDataV2(data) {
    this.dataV2 = new V2Disponibles();
    this.cuposDisponiblesApi = [];
    this.detallesDisponiblesApi = new Detalles();
    /* this.cupoService.getCuposAsignados(this.filtro.fecha).subscribe(
      res => { */
    this.loader.close();
    this.cuposDisponiblesApi = data.listado;
    this.detallesDisponiblesApi = data.detalles;
    this.loadDataProducto();
    this.getItemsProductos();
    /* },
    error => {
      this.loader.close();
    }) */
  }

  loadDataProducto() {
    let indice = 0;
    this.detallesReceptor = [];
    for (let index = 0; index < this.cuposDisponiblesApi.length; index++) {
      const listado = this.cuposDisponiblesApi[index];
      if (listado.destinos.length > 0) {
        for (let i = 0; i < listado.destinos.length; i++) {
          const destino = listado.destinos[i];
          if (destino.productos.length > 0) {
            for (let j = 0; j < destino.productos.length; j++) {
              const produc = destino.productos[j];
              if (produc.id_producto === this.filtro.id_producto) {
                produc.cupos.forEach((element) => {
                  let tempCupo = new Cupo();
                  tempCupo = element;
                  tempCupo.estadoCalculado = "";
                  if (element.cupoAsignadoUltimo !== null) {
                    let id_receptor = parseInt(element.cupoAsignadoUltimo.id);
                    let cuitReceptor = element.cupoAsignadoUltimo.receptorCuit;
                    let detalleDadorTemp = this.detallesReceptor.find(
                      (item) =>
                        item.cuitReceptor === cuitReceptor &&
                        item.id_producto == produc.id_producto
                    );
                    if (detalleDadorTemp === undefined) {
                      const detalle = new DetalleReceptor();
                      detalle.id_receptor = id_receptor;
                      detalle.cuitReceptor = cuitReceptor;
                      detalle.nombre_receptor = this.detallesDisponiblesApi.receptor[
                        cuitReceptor
                      ].nombreReceptor;
                      detalle.id_producto = produc.id_producto;
                      detalle.nombre_producto = this.detallesDisponiblesApi.producto[
                        produc.id_producto
                      ].nombreProducto;
                      detalle.total_cupos = 0;
                      detalle.ctg = 0;
                      detalle.sin_ctg = 0;
                      detalle.en_destino = 0;
                      detalle.descargado = 0;
                      detalle.cupos = [];

                      detalle.cupos.push(tempCupo);
                      this.detallesReceptor.push(detalle);
                    } else {
                      detalleDadorTemp.cupos.push(tempCupo);
                    }
                  } else {
                    let detalleDadorTemp = this.detallesReceptor.find(
                      (item) =>
                        item.cuitReceptor === this.mycuit &&
                        item.id_producto == produc.id_producto
                    );
                    if (detalleDadorTemp === undefined) {
                      const detalle = new DetalleReceptor();
                      detalle.id_receptor = this.myid_receptor;
                      detalle.nombre_receptor = this.myname;
                      detalle.cuitReceptor = this.mycuit;
                      detalle.id_producto = produc.id_producto;
                      detalle.total_cupos = 0;
                      detalle.por_asignar = 0;
                      detalle.por_vincular = 0;
                      detalle.ctg = 0;
                      detalle.sin_ctg = 0;
                      detalle.mas_50km = 0;
                      detalle.menos_50km = 0;
                      detalle.cargados = 0;
                      detalle.menos_50km_destino = 0;
                      detalle.en_destino = 0;
                      detalle.descargado = 0;
                      detalle.anulados = 0;
                      detalle.recuperar = false;
                      detalle.cupos = [];
                      detalle.cupos.push(tempCupo);
                      this.detallesReceptor.push(detalle);
                    } else {
                      detalleDadorTemp.cupos.push(tempCupo);
                    }
                  }
                });
              }
            }
          }
        }
      }
    }
    if (this.detallesReceptor.length > 0) {
      this.detallesReceptor.forEach((element) => {
        element.total_cupos = element.cupos.length;
        element.recuperar = false;
        for (let index = 0; index < element.cupos.length; index++) {
          const element1 = element.cupos[index];
          if (
            element1.id_pedido == null &&
            element1.estadoViaje == null &&
            (element1.idCupoEstado == null || element1.idCupoEstado == "1") &&
            element1.cupoAsignadoUltimo
          ) {
            if (
              element1.cupoAsignadoUltimo.dadorCuit == this.mycuit ||
              (element1.cupoAsignadoUltimo.receptorCuit == this.mycuit &&
                element1.cupoAsignadoUltimo.vinculado == "1")
            ) {
              element.recuperar = true;
            }
          }
          if (element1.idCupoEstado == "1") {
            element.sin_ctg = element.sin_ctg + 1;
            element1.estadoCalculado = "sin_ctg";
            continue;
          }
          if (element1.idCupoEstado == "2") {
            element.ctg = element.ctg + 1;
            element1.estadoCalculado = "ctg";
            continue;
          }
          if (element1.idCupoEstado == "3") {
            element.descargado = element.descargado + 1;
            element1.estadoCalculado = "descargado";
            continue;
          }
          if (element1.idCupoEstado == "5") {
              element.en_destino = element.en_destino + 1;
              element1.estadoCalculado = "en_destino";
            continue;
          }
          if (element1.idCupoEstado === null) {
            element.sin_ctg = element.sin_ctg + 1;
            element1.estadoCalculado = "sin_ctg";
            continue;
          }

        }
      });
    }
    this.dataSource.data = this.detallesReceptor;
  }

  cargarAlfanumerico(valor, row: DetalleReceptor) {
    this.filtro1.estado = valor;
    let someCupos: Cupo[] = [];
    let title = valor;
    let sin_ctg = false;
    switch (valor) {
      case "total":
        someCupos = row.cupos;
        title = " TODOS LOS CUPOS";
        break;
        case "ctg":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "ctg"
        );
        title = " CTG";
        break;
      case "sin_ctg":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "sin_ctg"
        );
        title = " SIN CTG";
        sin_ctg = true;
        break;
      case "en_destino":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "en_destino"
        );
        title = "EN DESTINO";
        break;
      case "descargado":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "descargado"
        );
        title = " DESCARGADOS";
        break;
      case "por_asignar":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "por_asignar"
        );
        title = " Por Asignar";
        break;
      case "por_vincular":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "por_vincular"
        );
        title = " Por Vincular";
        sin_ctg = true;
        break;

      case "mas_50km":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "mas_50km"
        );
        title = " Pendientes a  + 50 km";
        break;
      case "menos_50km":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "menos_50km"
        );
        title = " Pendientes a  - 50 km";
        break;
      case "cargados":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "cargados"
        );
        title = " Cargado";
        break;
      case "menos_50km_destino":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "menos_50km_destino"
        );
        title = " Menos 50 km del destino";
        break;

      /* case "anulados":
        someCupos = row.cupos.filter(
          (item) => item.estadoCalculado === "anulado"
        );
        title = "Anulados";
        break; */
      default:
        break;
    }
    if (someCupos.length > 0) {
      let heightPop: number = 30 + someCupos.length * 10;
      let heightPopUp: number = 55;
      if (heightPop > 80) heightPopUp = 80;
      else heightPopUp = heightPop;
      console.log('heightPopUp',heightPopUp);
      let dialogRef: MatDialogRef<any> = this.dialog.open(
        DetalleConsolidadoComponent,
        {
          width: "55vw",
          height: heightPopUp.toString() + "vh",
          disableClose: true,
          data: {
            title: title,
            payload: { cupos: someCupos, height: heightPopUp, sinCtg: sin_ctg },
          },
        }
      );
    }
  }

  aplicarFiltro(element, cmp) {
    if (element == "fecha") {
      this.filtro.fecha = this.homeService.formatoFecha(cmp.value, "amd", "-");
      this.filtro1.fecha = this.homeService.formatoFecha(cmp.value, "amd", "-");
      this.cambiarFecha.emit({ fecha: this.filtro.fecha });
      // this.loadDataV2();
    } else {
      this.filtro.id_producto = cmp;
      this.filtro1.id_producto = cmp;
      if (cmp === 1 || cmp === 2 || cmp === 3 || cmp === 5) {
        this.filtrarForm.controls["selectedProducto"].setValue(null);
      }
      this.loadDataProducto();
    }
  }

  getItemsProductos() {
    this.otrosproductos = [];
    for (let index = 0; index < this.cuposDisponiblesApi.length; index++) {
      const dador = this.cuposDisponiblesApi[index];
      if (dador.destinos.length > 0) {
        for (let i = 0; i < dador.destinos.length; i++) {
          const destino = dador.destinos[i];
          if (destino.productos.length > 0) {
            for (let j = 0; j < destino.productos.length; j++) {
              const produc = destino.productos[j];
              if (
                produc.id_producto !== 1 &&
                produc.id_producto !== 2 &&
                produc.id_producto !== 3 &&
                produc.id_producto !== 5
              ) {
                const temp = {
                  id: produc.id_producto,
                  descripcion: this.detallesDisponiblesApi.producto[
                    produc.id_producto
                  ].nombreProducto,
                };
                this.otrosproductos.push(temp);
              }
            }
          }
        }
      }
    }
  }

  accionRecuperar(cupo: DetalleReceptor) {
    let valorFecha = this.homeService.formatoFecha(
      this.filtrarForm.controls["selectedFecha"].value,
      "amd",
      "-"
    );
    let title = "RECUPERAR CUPOS";
    let dialogRef: MatDialogRef<any> = this.dialog.open(RecuperarComponent, {
      width: "95vw",
      height: "96vh",
      disableClose: false,
      data: {
        title: title,
        payload: {
          fecha: valorFecha,
          solicitudCupos: cupo,
          simple: true,
          filtro: this.filtro,
          nombreReceptor: cupo.nombre_receptor,
          producto: cupo.nombre_producto,
        },
      },
    });
    dialogRef.afterClosed().subscribe((res) => {
      if (!res) {
        // If user press cancel
        return;
      }
      //this.loadDataV2();
      this.cambiarFecha.emit({ fecha: valorFecha });
      return;
    });
  }
}
