// Generated by https://quicktype.io

export interface CuposDisponible {
  origen: Origen;
  is_checkend: boolean;
  id: string;
  idCupoTerminal: string;
  idCupoEstado: string | null;
  cartaPorte: string | null;
  ctg: string | null;
  dominio: string | null;
  fecha: Date;
  idCuitDestinatario: string;
  idCuitRepresentanteEntregador: string | null;
  dadorCuit: string;
  cosecha: string | null;
  id_producto: string;
  id_destino: string;
  id_derivacion: string;
  nroContrato: string | null;
  id_pedido: string | null;
  en_viaje: string | null;
  nombreDestinatario: string;
  observaciones: string | null;
  id_demanda: string | null;
  nombreChofer: string | null;
  cuitChofer: string | null;
  nombreDador: string;
  patente: string;
  destino: Destino | null;
  producto: Destino | null;
  derivacion: Derivacion | null;
  transportadora: string;
  pedido?: boolean;
  entregador?: boolean;
  fechaCupoFormateada: string | null;
}

export interface Derivacion {
  id: string;
  id_cupo: string;
  id_transportadora: string;
  transportadora: string;
  fecha_derivacion: Date;
  canal: string;
}

export interface Destino {
  id: string;
  descripcion: string;
}

export interface Origen {
  id: string;
  descripcion: string;
}

export interface DestinoFilter{
  id_destino: string,
  descripcion: string
}

export interface Transportadora {
  id:                   number;
  id_usuario:           string;
  cuit:                 string;
  nombre_intermediario: string;
}

export interface OrigenDestino {
  id_origen: string;
  descripcion: string;
}
