import { Component, OnInit } from "@angular/core";
import { CupoRecuperarV2 } from "@muvin/models";
import { AppLoaderService, MessageService, UserService } from "@muvin/services";
import * as moment from "moment";
import { HomeService } from "../../home/home.service";
import { CupoService } from "../cupo.service";

// Generated by https://quicktype.io
export class Items {
  id: number;
  descripcion: string;
}

export class CentroSinEMail {
  cuit: string;
  razon_social: string;
  email: string[];
  id: number;
  omitir: true;
}

export class DiaSemana {
  id: number;
  dia: string;
  dia_semana: string;
  dia_semana_string: string;
  mes: string;
  fecha: string;
}

@Component({
  selector: "app-cuponera",
  templateUrl: "./cuponera.component.html",
  styleUrls: ["./cuponera.component.scss"],
})
export class CuponeraComponent implements OnInit {
  selectedTab = 0;
  public searchDateString: string = "";
  public fechaDesdeRecuperar: string = "";
  public fechaHastaRecuperar: string = "";
  now = new Date();
  cuposDadoresApiV3: any[] = [];
  cuposDadoresApiV2: any[] = [];
  cuposApiV3: any[] = [];
  cuposDetallesApiV3: any[] = [];
  cuposDetallesApiV2: any[] = [];
  demandasV1: any;
  detallesApiV3: any[] = [];
  solicitudesApiV3: any[] = [];
  usaCupera: string = '';

  productos: Items[] = [];
  cuposRecuperar: CupoRecuperarV2[] = [];
  detallesRecuperar: any;
  myData: any = {
    micuit: "",
    soyCorredor: false,
    solicitaCupos: false,
    formularioCupera: false,
    lbCorredor: "",
    name: "",
  };
  notificaciones = 0;
  listSinEmail: CentroSinEMail[] = [];
  dia5Moment: moment.Moment = moment();
  dias: DiaSemana[] = [];
  dataCupera3 = {
    cupos: [],
    detalles: [],
    solicitudes: [],
    fecha: '',
    dias: []
  };

  constructor(
    private homeService: HomeService,
    private cupoService: CupoService,
    private loader: AppLoaderService,
    private messageService: MessageService,
    private userService: UserService
  ) {
    this.myData.micuit = localStorage.getItem("cuit_cuil");
    this.myData.myname = localStorage.getItem("nameUser");
    this.myData.solicitaCupos =
      localStorage.getItem("esDestinatario") === "1" ? false : true;
    this.myData.formularioCupera =
      localStorage.getItem("formularioCupera") === "2" ? true : false;
  }

  ngOnInit() {
    this.usaCupera = localStorage.getItem("usaCupera");
    this.searchDateString = this.homeService.formatoFecha(this.now, "amd", "-");
    this.loadData(this.searchDateString, 0, true);
    this.getItemsProductos();
    this.fechaDesdeRecuperar = moment().format("YYYY-MM-DD");
    this.fechaHastaRecuperar = moment().add(3, "days").format("YYYY-MM-DD");
    this.loadCuposRecuperar(
      this.fechaDesdeRecuperar,
      this.fechaHastaRecuperar,
      false
    );
    this.userService.esCorredor(this.myData.micuit).subscribe(
      (res) => {
        this.myData.soyCorredor = res.data.esCorredor;
        if (this.myData.soyCorredor) {
          this.myData.lbCorredor = "SIN OTRO CORREDOR";
        } else {
          this.myData.lbCorredor = "DIRECTO";
        }
      },
      (error) => { }
    );
    this.getNotificaciones();
  }
  selectTab(event) {
    this.selectedTab = event;
  }

  chanceDate(event, opcion): void {
    this.searchDateString = event.fecha;
    this.loadData(this.searchDateString, opcion, true);
  }

  chanceDateRecuperar(event): void {
    this.fechaDesdeRecuperar = event.fechaDesde;
    this.fechaHastaRecuperar = event.fechaHasta;
    this.loadCuposRecuperar(
      this.fechaDesdeRecuperar,
      this.fechaHastaRecuperar,
      true
    );
    //this.searchDateString = event.fecha;
  }

  recuperarAccion(): void {
    this.loadCuposRecuperar(
      this.fechaDesdeRecuperar,
      this.fechaHastaRecuperar,
      false
    );
    this.loadData(this.searchDateString, 0, false);
  }

  loadRecuperarAccion(): void {
    this.loadCuposRecuperar(
      this.fechaDesdeRecuperar,
      this.fechaHastaRecuperar,
      false
    );
  }

  loadData(fecha, opcion, load: boolean) {
    this.cuposDadoresApiV3 = [];
    this.cuposDetallesApiV3 = [];
    if (load) {
      this.loader.open("Por favor espere...");
    }
    this.llenarArrayDia(fecha);
    const usaCupera = localStorage.getItem("usaCupera");
    switch (usaCupera) {
      case "1":
        if (opcion == 0) {
          this.messageService.sendMessage("IniciarProducto", "0", {});
        }
        this.cupoService.getV3CuposAsignados(fecha).subscribe(
          (res) => {
            this.loader.close();
            this.cuposDadoresApiV3 = res.data.listado;
            this.cuposDetallesApiV3 = res.data.detalles;
            const data = {
              listado: res.data.listado,
              detalles: res.data.detalles,
            };
            switch (opcion) {
              case 0:
                this.messageService.sendMessage("Asignacion", "0", data);
                break;
              case 1:
                this.messageService.sendMessage("PanelConsolidado", "1", data);
                break;
              /* case 2:
                this.messageService.sendMessage("DetalleDador", "2", data);
                break; */
              case 2:
                this.messageService.sendMessage("AsignadosReceptor", "2", data);
                break;


              default:
                break;
            }
          },
          (error) => {
            this.loader.close();
          }
        );
        this.cupoService.getDemandaCupos(fecha).subscribe(
          (res) => {
            this.demandasV1 = {
              demandantes: res.data.demandantes,
              detalles: res.data.detalles,
            };
            switch (opcion) {
              case 0:
                this.messageService.sendMessage(
                  "DemandasV1",
                  "0",
                  this.demandasV1
                );
                break;
              default:
                break;
            }
          },
          (error) => {
            this.loader.close();
          }
        );
        break;
      case "2":
        this.cupoService.getV3ListadoCuposAsignados(fecha).subscribe(
          (res) => {
            if (this.loader !== null) {
              this.loader.close();
            }
            this.cuposApiV3 = res.data.cupos;
            this.detallesApiV3 = res.data.detalles;
            this.solicitudesApiV3 = res.data.solicitudes;
            const data = {
              cupos: res.data.cupos,
              detalles: res.data.detalles,
              solicitudes: res.data.solicitudes,
              fecha: fecha,
              dias: this.dias,
            };
            switch (opcion) {
              case 0:
                this.messageService.sendMessage("AsignacionV3", "0", data);
                break;
              default:
                break;
            }
          },
          (error) => {
            this.loader.close();
          }
        );

        this.cupoService.getV3CuposAsignados(fecha).subscribe(
          (res) => {
            if (this.loader !== null) {
              this.loader.close();
            }
            this.cuposDadoresApiV2 = res.data.listado;
            this.cuposDetallesApiV2 = res.data.detalles;

            const data = {
              listado: res.data.listado,
              detalles: res.data.detalles,
            };
            switch (opcion) {
              case 1:
                this.messageService.sendMessage("PanelConsolidadoV2", "1", data);
                break;
              default:
                break;
            }
          },
          (error) => {
            this.loader.close();
          }
        );
        break;
      case "3":

        this.cupoService.getListadoCuposAsignadosC3(fecha).subscribe(
          (res) => {
            if (this.loader !== null) {
              this.loader.close();
            }

            this.dataCupera3 = {
              cupos: res.data.cupos,
              detalles: res.data.detalles,
              solicitudes: res.data.solicitudes,
              fecha: fecha,
              dias: this.dias,
            };
            /* switch (opcion) {
              case 0:
                this.messageService.sendMessage("AsignacionC3", "0", data);
                break;
              default:
                break;
            } */
          },
          (error) => {
            this.loader.close();
          }
        );
        this.cupoService.getV3CuposAsignados(fecha).subscribe(
          (res) => {
            if (this.loader !== null) {
              this.loader.close();
            }
            this.cuposDadoresApiV2 = res.data.listado;
            this.cuposDetallesApiV2 = res.data.detalles;

            const data = {
              listado: res.data.listado,
              detalles: res.data.detalles,
            };
            switch (opcion) {
              case 1:
                this.messageService.sendMessage("PanelConsolidadoV2", "1", data);
                break;
              default:
                break;
            }
          },
          (error) => {
            this.loader.close();
          }
        );
        break;

      default:
        break;
    }
  }

  getItemsProductos() {
    this.cupoService.getProductosCentro().subscribe((data) => {
      this.productos = data.data;
      this.messageService.sendMessage("productos", '1', this.productos);
    });
  }

  loadCuposRecuperar(fechaDesde, fechaHasta, load: boolean) {
    this.cuposRecuperar = [];
    /* if (load) {
      this.loader.open("Por favor espere(2)...");
    } */
    this.cupoService.getV3CuposRecuperar(fechaDesde, fechaHasta).subscribe(
      (res) => {
        if (this.loader !== null) {
          this.loader.close();
        }
        this.cuposRecuperar = res.data.listado;
        this.detallesRecuperar = {
          corredor_contraparte: res.data.corredor_contraparte,
          destinos: res.data.destinos,
          productos: res.data.productos,
          destinatarios: res.data.destinatarios,
        };
        const data = {
          listado: res.data.listado,
          detalles: this.detallesRecuperar,
        };
        this.messageService.sendMessage("RecuperarCupoV3", "1", data);
      },
      (error) => {
        this.loader.close();
      }
    );
  }

  getNotificaciones() {
    this.listSinEmail = [];
    this.cupoService.getNotificacionesPendientes().subscribe(
      (data) => {
        this.notificaciones = parseInt(data.data.cantidad_pendiente)
          ? parseInt(data.data.cantidad_pendiente)
          : 0;
        if (data.data.centros_pendientes_sin_email.length > 0) {
          data.data.centros_pendientes_sin_email.forEach((element) => {
            let temp = this.listSinEmail.find(
              (item) => item.cuit == element.cuit
            );
            if (temp == undefined) {
              let item = new CentroSinEMail();
              item.cuit = element.cuit;
              item.razon_social = element.razon_social;
              item.email = [];
              item.id = parseInt(element.id);
              this.listSinEmail.push(item);
            }
          });
        }
        if (this.listSinEmail.length > 0) {
          this.messageService.sendMessage(
            "CentroSinEmail",
            "1",
            data.data.centros_pendientes_sin_email
          );
        }
      },
      (error) => { }
    );
  }

  llenarArrayDia(fecha) {
    this.dia5Moment = moment(fecha);
    const toTwoDigits = (num) => (num < 10 ? "0" + num : num);
    this.dias = [];
    for (let index = 0; index < 7; index++) {
      var currentTime: moment.Moment = moment(fecha).add(index, "days");
      let dia = new DiaSemana();
      dia.id = index;
      dia.dia = toTwoDigits(currentTime.date());
      dia.dia_semana = currentTime.weekday().toString();
      dia.dia_semana_string = this.dameDiaSemanaString(dia.dia_semana);
      dia.mes = toTwoDigits(currentTime.month() + 1);
      dia.fecha = currentTime.year().toString() + "-" + dia.mes + "-" + dia.dia;
      this.dias.push(dia);
    }
  }
  dameDiaSemanaString(dias) {
    let dia = "";
    switch (dias) {
      case "0":
        dia = "DOM";
        break;
      case "1":
        dia = "LUN";
        break;
      case "2":
        dia = "MAR";
        break;
      case "3":
        dia = "MIE";
        break;
      case "4":
        dia = "JUE";
        break;
      case "5":
        dia = "VIE";
        break;
      case "6":
        dia = "SAB";
        break;

      default:
        break;
    }
    return dia;
  }
}
