// Generated by https://quicktype.io

export interface Viaje {
  id: string;
  idCupoTerminal: string;
  idCupoEstado: string;
  cartaPorte: null;
  ctg: null;
  dominio: null;
  fecha: Date;
  idCuitDestinatario: string;
  idCuitRepresentanteEntregador: null;
  proveedorCuit: string;
  cosecha: null;
  id_producto: string;
  id_destino: string;
  nroContrato: null;
  id_pedido: string;
  en_viaje: string;
  nombreDestinatario: string;
  observaciones: null;
  id_demanda: null;
  nombreChofer: string | null;
  cuitChofer: string | null;
  nombreProveedor: string;
  destino: RazonSocial;
  producto: RazonSocial;
  origen: RazonSocial;
}

export interface RazonSocial {
  id: string;
  descripcion: string;
}
